from numpy import ndarray


def quick_sort_cy(nums: ndarray) -> None: ...
def partition_cy(nums: ndarray) -> int: ...
def merge_cy(nums: ndarray, lo: int, mid: int, hi: int) -> None: ...
def merge_sort_cy(nums: ndarray) -> None: ...
